import type { Metadata } from 'next'
import './globals.css'
import localFont from 'next/font/local'
import NavBar from '@/components/NavBar'

const CastoroRegular = localFont({
  src: '../fonts/Castoro-Regular.ttf',
  display: 'swap'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={CastoroRegular.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
